import { AudioLines, ShieldAlert, Zap, ArrowDown } from 'lucide-react';

interface HeroProps {
  onAnalyze: () => void;
}

export default function Hero({ onAnalyze }: HeroProps) {
  return (
    <section className="relative pt-32 pb-20 overflow-hidden">
      {/* Background grid + glows */}
      <div className="absolute inset-0 -z-10">
        <div
          className="absolute inset-0 opacity-[0.04]"
          style={{
            backgroundImage:
              'linear-gradient(#06b6d4 1px, transparent 1px), linear-gradient(90deg, #06b6d4 1px, transparent 1px)',
            backgroundSize: '48px 48px',
          }}
        />
        <div className="absolute top-0 left-1/4 w-[36rem] h-[36rem] bg-cyan-500/10 rounded-full blur-[120px]" />
        <div className="absolute bottom-0 right-1/4 w-[30rem] h-[30rem] bg-red-500/10 rounded-full blur-[120px]" />
      </div>

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-1.5 mb-8">
            <Zap className="h-3.5 w-3.5 text-cyan-400" />
            <span className="text-xs font-medium tracking-wide text-cyan-300 uppercase">
              Real-time AI Audio Detection
            </span>
          </div>

          <h1 className="max-w-4xl text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-white leading-[1.1]">
            Protect Your Family from
            <span className="block mt-2 bg-gradient-to-r from-cyan-400 via-cyan-300 to-red-400 bg-clip-text text-transparent">
              AI Voice Scams & Deepfakes
            </span>
          </h1>

          <p className="mt-6 max-w-2xl text-base sm:text-lg text-slate-400 leading-relaxed">
            Upload any voice message and instantly detect whether it was generated by AI
            deepfake technology. Stop scammers from impersonating your loved ones.
          </p>

          <div className="mt-10 flex flex-col sm:flex-row items-center gap-4">
            <button
              onClick={onAnalyze}
              className="group relative inline-flex items-center gap-3 rounded-xl bg-gradient-to-r from-cyan-500 to-cyan-600 px-7 py-4 text-sm font-semibold text-slate-950 shadow-lg shadow-cyan-500/25 transition-all hover:shadow-cyan-400/40 hover:scale-[1.02] active:scale-[0.98]"
            >
              <AudioLines className="h-5 w-5" />
              Analyze Audio File
              <span className="absolute inset-0 rounded-xl bg-white/20 opacity-0 group-hover:opacity-100 transition-opacity" />
            </button>
            <a
              href="#safety"
              className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-6 py-4 text-sm font-medium text-slate-300 transition-colors hover:bg-white/10"
            >
              <ShieldAlert className="h-4 w-4 text-red-400" />
              Family Safety Tips
            </a>
          </div>

          <button
            onClick={onAnalyze}
            className="mt-16 text-slate-500 hover:text-cyan-400 transition-colors animate-bounce"
            aria-label="Scroll to scanner"
          >
            <ArrowDown className="h-5 w-5 mx-auto" />
          </button>
        </div>
      </div>
    </section>
  );
}
